# 1. Blocul SEO: Prinde www.rrdesign.ro si redirectioneaza catre varianta scurta (cu https)
server {
    listen 80;
    server_name www.rrdesign.ro;
    
    return 301 https://rrdesign.ro$request_uri;
}

# 2. Blocul Principal: Servește aplicația ta React
server {
    listen 80;
    server_name rrdesign.ro localhost; # Am specificat numele domeniului aici

    # Serve static files (React App)
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Error pages
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}